export const SYLLABUS = {
  '10th': {
    Science: [
      'Chemical Reactions',
      'Acids, Bases and Salts',
      'Metals and Non-metals',
      'Carbon and its Compounds',
      'Life Processes',
      'Control and Coordination',
      'How do Organisms Reproduce',
      'Heredity and Evolution',
      'Light - Reflection',
      'The Human Eye and Colourful World',
      'Electricity',
      'Magnetic Effects of Electric Current',
      'Our Environment',
    ],
    Mathematics: [
      'Real Numbers',
      'Polynomials',
      'Pair of Linear Equations',
      'Quadratic Equations',
      'Arithmetic Progressions',
      'Triangles',
      'Coordinate Geometry',
      'Introduction to Trigonometry',
      'Applications of Trigonometry',
      'Circles',
      'Surface Areas and Volumes',
      'Statistics',
      'Probability',
    ],
    'Social Science': [
      'Rise of Nationalism in Europe',
      'Nationalism in India',
      'Resources and Development',
      'Agriculture',
      'Power Sharing',
      'Federalism',
      'Money and Credit',
      'Globalization and Indian Economy',
      'Political Parties',
      'Outcomes of Democracy',
    ],
    English: [
      'Reading Comprehension',
      'Tenses and Modals',
      'Subject-Verb Concord',
      'Reported Speech',
      'Analytical Paragraph Writing',
      'Formal Letter Writing',
    ],
    'Computer Applications': [
      'Basics of Information Technology',
      'Cyberethics and Online Safety',
      'HTML and Web Design',
      'Python Programming Basics',
    ],
  },
  '12th': {
    Physics: [
      'Electrostatics',
      'Current Electricity',
      'Magnetic Effects of Current & Magnetism',
      'Electromagnetic Induction',
      'Alternating Current',
      'Electromagnetic Waves',
      'Optics',
      'Dual Nature of Radiation',
      'Atoms and Nuclei',
      'Semiconductor Electronics',
      'Thermodynamics',
    ],
    Chemistry: [
      'Solutions',
      'Electrochemistry',
      'Chemical Kinetics',
      'd and f Block Elements',
      'Coordination Compounds',
      'Haloalkanes and Haloarenes',
      'Alcohols, Phenols and Ethers',
      'Aldehydes, Ketones and Carboxylic Acids',
      'Amines',
      'Biomolecules',
    ],
    Mathematics: [
      'Relations and Functions',
      'Inverse Trigonometric Functions',
      'Matrices and Determinants',
      'Continuity and Differentiability',
      'Applications of Derivatives',
      'Integrals',
      'Differential Equations',
      'Vector Algebra',
      'Three Dimensional Geometry',
      'Linear Programming',
      'Probability',
    ],
    Biology: [
      'Sexual Reproduction in Flowering Plants',
      'Human Reproduction',
      'Reproductive Health',
      'Principles of Inheritance and Variation',
      'Molecular Basis of Inheritance',
      'Human Health and Disease',
      'Biotechnology - Principles and Applications',
      'Ecosystem and Biodiversity',
    ],
    'Computer Science': [
      'Python Functions and File Handling',
      'Data Structures',
      'SQL',
      'Boolean Algebra',
      'Networking',
      'Cyber Safety and Security',
    ],
    Economics: [
      'National Income Accounting',
      'Money and Banking',
      'Determination of Income and Employment',
      'Government Budget',
      'Indian Economic Development',
      'Human Capital Formation and Rural Development',
    ],
    'Business Studies': [
      'Principles of Management',
      'Business Environment',
      'Planning and Organizing',
      'Financial Management',
      'Marketing Management',
      'Consumer Protection',
    ],
  },
};
